version: '3.8'

services:
  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: load-balancer
    ports:
      - "8090:8090"
    environment:
      SPRING_RABBITMQ_HOST: data-collection-broker
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: root
      SPRING_RABBITMQ_PASSWORD: root
      LOAD_BALANCER_REPLICAS: 3
      LOAD_BALANCER_STRATEGY: consistent-hashing
    networks:
      - synch-rabbitmq_sd-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/load-balancer/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  synch-rabbitmq_sd-network:
    external: true

