global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    exposedByDefault: false
    watch: true
  file:
    filename: /etc/traefik/traefik.yaml
    watch: true

http:
  middlewares:
    cors-headers:
      headers:
        accessControlAllowOriginList:
          - "http://localhost:3000"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "*"
        accessControlExposeHeaders:
          - "*"
        accessControlMaxAge: 3600
        accessControlAllowCredentials: true
    strip-api:
      stripPrefix:
        prefixes:
          - "/api"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true