spring.application.name=load-balancer
server.port=8090
spring.rabbitmq.host=data-collection-broker
spring.rabbitmq.port=5672
spring.rabbitmq.username=root
spring.rabbitmq.password=root
spring.rabbitmq.virtual-host=/

# Load Balancer Configuration
load-balancer.replicas=3
load-balancer.strategy=consistent-hashing
load-balancer.queue.device-data=device.data
load-balancer.queue.monitoring-ingest-prefix=monitoring.ingest.

# Logging
logging.level.root=INFO
logging.level.com.sscl.lb=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
